### ISSUE TITLE
Add partners

### ISSUE THREAD

**Issue by cseas** [glugmv/glug_website_django#29]
Modify the site homepage to feature our club partners:
- [Microsoft Student Partners](https://studentpartners.microsoft.com/en-us)
- [Mozilla India](https://mozillaindia.org/)
- [MLH Localhost](https://localhost.mlh.io/)

**Comment by ramanaditya** [comment]
Where do you want to add all these partners details, in the footer?

**Comment by cseas** [comment]
Both, in the footer and the main website homepage. 

Seems like a good replacement for the "Why choose us" section on the homepage, since that section doesn't provide much useful information anyway.

The logos of the partners also need to be added wherever in the body the partners are added.

**Comment by ramanaditya** [comment]
Updated
